### ISSUE TITLE
with linkify, broke links

### ISSUE THREAD

**Issue by itenisz** [markdown-it/markdown-it-abbr#4]
If linkify: true in markdown-it, and link url contains an abbr word, then broke the link.

**Comment by puzrin** [comment]
https://markdown-it.github.io/ share example please.

**Comment by itenisz** [comment]
The problem with slugified links with '-'.

Example:
http://example.com/this-is-broken-example/
*[broken]: This link is broken

Snippet:
https://goo.gl/qMYA50

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it-abbr/commit/94396e64b349bf4a7619c25385f26256dcf1f182
