### ISSUE TITLE
uc.micro incorrectly placed in devDependencies

### ISSUE THREAD

**Issue by Dashed** [markdown-it/markdown-it-abbr#5]
@puzrin  @rlidwka 
This commit introduced usages of `uc.micro` which was incorrectly placed in `devDependencies:

https://github.com/markdown-it/markdown-it-abbr/commit/94396e64b349bf4a7619c25385f26256dcf1f182

I was getting these webpack errors:

```js
ERROR in ./~/markdown-it-abbr/index.js
Module not found: Error: Cannot resolve module 'uc.micro/categories/P/regex' in /path/to/node_modules/markdown-it-abbr
 @ ./~/markdown-it-abbr/index.js 11:23-61

ERROR in ./~/markdown-it-abbr/index.js
Module not found: Error: Cannot resolve module 'uc.micro/categories/Z/regex' in /path/to/node_modules/markdown-it-abbr
 @ ./~/markdown-it-abbr/index.js 12:23-61
```

**Comment by puzrin** [comment]
Thanks for report. That should be `md.utils.lib.ucmicro...` instead of `require`

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it-abbr/commit/921e94c72cbd5461715a2ba7b3191b312d3b8587

**Comment by Dashed** [comment]
Thanks for prompt fix! :+1: :tada:
