### ISSUE TITLE
Should abbr is inline element?

### ISSUE THREAD

**Issue by cuonghuunguyen** [markdown-it/markdown-it-abbr#9]
Hi, thanks for the great library. Today, I tried rendering abbr using inline renderer but it doesn't work. 
According to this, https://www.w3schools.com/html/html_blocks.asp, abbr seems to be an inline element. Do you think we should add it to the inline renderer?

**Comment by puzrin** [comment]
I think here is confusion between input markup (md) and output markup (html). Abbr on input (markdown) are references-like structs. Those can not part of inline parser.
